name: Rastreador Amazon

on:
  schedule:
    - cron: '0 8 * * *'  # Se ejecuta a las 08:00 UTC todos los días
  workflow_dispatch:      # Permite ejecutarlo manualmente con un botón

permissions:
  contents: write         # PERMISO CRÍTICO: Para poder guardar el CSV

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código del repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Ejecutar Rastreador
        run: python main.py

      - name: Guardar cambios (CSV)
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'action@github.com'
          git add historial_precios.csv
          git commit -m "Actualización automática de precios" || echo "Nada que actualizar"
          git push
